language: objective-c

before_install:
  - cd GoogleMediaFrameworkDemo

script:
  # TODO: Add 'test' flag here once tests work on travis-ci server.
  - xctool build -workspace GoogleMediaFrameworkDemo.xcworkspace -scheme GoogleMediaFrameworkDemo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
