source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "6.1"

pod "GoogleMediaFramework", :path => "../"
# Demo app shows how to integrate with the Google IMA SDK, but this is optional.
pod "GoogleAds-IMA-iOS-SDK", "3.0.beta13"
